# Generated by Django 4.1.7 on 2023-03-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("-date_added",)},
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
