# Generated by Django 4.1.7 on 2023-03-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_product_in_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="in_stock",
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
