# Generated by Django 4.1.7 on 2023-04-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_remove_product_in_stock_product_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
