# Generated by Django 4.1.7 on 2023-04-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_marque"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Marque",
            new_name="Brand",
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="product.brand",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_sale",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
