# Generated by Django 4.1.7 on 2023-04-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_wish"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value_sold",
                    models.IntegerField(blank=True, max_length=3, null=True),
                ),
            ],
        ),
    ]
