# Generated by Django 4.1.7 on 2023-04-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_sold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
