# Generated by Django 4.1.7 on 2023-04-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_alter_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sold",
            name="value_sold",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
