# Generated by Django 4.1.7 on 2023-04-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_alter_product_price_sale"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sold",
            new_name="Sale",
        ),
    ]
