# Generated by Django 4.1.7 on 2023-04-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_rename_sold_sale"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="value_sold",
            new_name="sale_value",
        ),
    ]
