# Generated by Django 4.1.7 on 2023-04-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_alter_product_options_alter_wish_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="sale_value",
            field=models.IntegerField(null=True),
        ),
    ]
