# Generated by Django 4.1.7 on 2023-04-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0019_alter_sale_sale_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="sale_value",
            field=models.IntegerField(default=None),
        ),
    ]
